name: GitHub Security Alerts for Jira

on: workflow_dispatch

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitHub Security Alerts with Jira
        uses: reload/github-security-jira@v1.3.1
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://rs2kp.atlassian.net
          JIRA_USER: ryanslater2@kpmg.com
          JIRA_PROJECT: GT
          JIRA_WATCHERS: kintsang@kpmg.com
