name: GitHub Security Alerts for Jira

on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://rs2kp.atlassian.net
          JIRA_USER: ryanslater2@kpmg.com
          JIRA_PROJECT: GT
          JIRA_ISSUE_TYPE: Security
